<?php

// products
$products = [
    'pistol' => [
        ['id' => 'pistol-1', 'name' => 'Glock 17', 'price' => 24000, 'image' => 'glck17.png', 'description' => 'Glock 17 is a 9×19mm, polymer-framed, striker-fired pistol with a standard 17-round magazine. It is renowned for its reliability, simplicity, and widespread use by law enforcement and military forces around the world.'],
        ['id' => 'pistol-2', 'name' => 'Beretta 92FS', 'price' => 24600, 'image' => 'beretta.png', 'description' => 'The Beretta 92/92FS is a reliable 9×19mm service pistol, typically with a 15-round magazine, known for its open-slide design and widespread military and police use.'],
        ['id' => 'pistol-3', 'name' => 'SIG Saucer P320', 'price' => 23800, 'image' => 'ssig.png', 'description' => 'The SIG Sauer P320 is a modular, striker-fired pistol with a serialized fire-control unit that allows swapping grip modules, slides, and calibers, and is praised for its consistent trigger, ergonomic design, and reliability.'],
        ['id' => 'pistol-4', 'name' => 'CZ 75', 'price' => 25000, 'image' => 'cz.png','description' => 'The CZ 75 is a 9×19mm semi-automatic pistol known for its all-steel construction, smooth ergonomics, and excellent accuracy favored by military and sport shooters.'],
        ['id' => 'pistol-5', 'name' => 'Heckler & Koch VP9', 'price' => 25350, 'image' => 'vp9.png', 'description' => 'The Heckler & Koch VP9 is a striker-fired 9×19mm pistol with a polymer frame and interchangeable backstraps and lateral grip panels, celebrated for its excellent ergonomics, light trigger, and reliability.'],
        ['id' => 'pistol-6', 'name' => 'Smith & Wesson M&P9', 'price' => 24950, 'image' => 'm_p9.png', 'description' => 'The Smith & Wesson M&P9 is a polymer-frame, striker-fired 9×19mm service pistol designed for law-enforcement and civilian use, noted for its ergonomics, reliability, and configurable grip options.'],
        ['id' => 'pistol-7', 'name' => 'Glock 19', 'price' => 24300, 'image' => 'glock19.png','description' => 'The Glock 19 is a compact, striker-fired 9×19mm pistol—the shorter carry version of the Glock 17—typically using a 15-round magazine and popular for both concealed carry and duty use.']

    ],
    'revolver' => [
        ['id' => 'revolver-1', 'name' => 'Smith & Wesson Model 686', 'price' => 87200, 'image' => '686.png', 'description' => 'The Smith & Wesson Model 686 is an L-frame, six-shot revolver chambered in .357 Magnum (also .38 Special) with double-action/single-action operation, valued for its balance and durability for duty and range use.'],
        ['id' => 'revolver-2', 'name' => 'Coly Python', 'price' => 88100, 'image' => 'coly.png', 'description' => 'The Colt Python is a premium double-action/single-action .357 Magnum revolver renowned for its smooth trigger, accurate barrel, and finely finished construction, popular with collectors and target shooters.'],
        ['id' => 'revolver-3', 'name' => 'Ruger LCR', 'price' => 87550, 'image' => 'lcr.png', 'description' => 'The Ruger LCR is a lightweight, compact double-action-only revolver with a polymer/composite frame and smooth trigger, commonly chambered in .38 Special or .357 Magnum and designed for concealed carry and easy handling.'],
        ['id' => 'revolver-4', 'name' => 'Colt Single Action Army', 'price' => 89500, 'image' => 'colt.png', 'description' => 'The Colt Single Action Army is a single-action, six-shot revolver introduced in 1873, celebrated for its rugged construction, historical military and frontier use, and iconic status in Western heritage.'],
        ['id' => 'revolver-5', 'name' => 'Ruger GP100', 'price' => 89000, 'image' => 'gp100.png', 'description' => 'The Ruger GP100 is a robust all-steel double-action revolver, commonly chambered in .357 Magnum with a six-round cylinder, prized for its durability, strong lockwork, and suitability for duty and heavy-caliber shooting.'],
        ['id' => 'revolver-6', 'name' => 'Taurus Model 66', 'price' => 88900, 'image' => 'taurus.png', 'description' => 'The Taurus Model 66 is a stainless-steel, six-shot double-action/single-action revolver chambered for .357 Magnum (and .38 Special), valued for its solid construction, controllability, and good value for duty or personal defense.'],
        ['id' => 'revolver-7', 'name' => 'Smith & Wesson Model 629', 'price' => 87950, 'image' => '629.png', 'description' => 'The Smith & Wesson Model 629 is a stainless N-frame, six-shot revolver chambered for .44 Magnum (and .44 Special) with double-action/single-action operation, prized for its heavy, durable construction and suitability for hunting and big-bore target shooting.']
                
    ],
    'SMG' => [
        ['id' => 'smg-1', 'name' => 'Heckler & Koch MP5', 'price' => 150500, 'image' => 'mp5.png', 'description' => 'The Heckler & Koch MP5, developed in the 1960s, is a widely used closed‑bolt, roller‑delayed blowback submachine gun prized for its accuracy and low recoil.'],
        ['id' => 'smg-2', 'name' => 'IMI Uzi', 'price' => 120000, 'image' => 'uzi.png', 'description' => 'The IMI Uzi is a compact, early‑1950s submachine gun featuring a telescoping bolt and magazine‑in‑grip layout, prized for its simple design, rugged reliability, and short overall length.'],
        ['id' => 'smg-3', 'name' => 'Thompson', 'price' => 145200, 'image' => 'thompson.png', 'description' => 'The Thompson submachine gun (1918) is an iconic .45 ACP SMG famed for Prohibition‑era use and WWII service, known for its high rate of fire and distinctive silhouette.'],
        ['id' => 'smg-4', 'name' => 'PPSh-41', 'price' => 140500, 'image' => 'ppsh.png', 'description' => 'The PPSh‑41 is a mass‑produced Soviet WWII submachine gun developed after the Winter War, chambered in 7.62×25mm Tokarev and famed for its high‑capacity 35‑round box or 71‑round drum magazines and brutal close‑quarters effectiveness.'],
        ['id' => 'smg-5', 'name' => ' FN P90', 'price' => 115000, 'image' => 'p90.png', 'description' => 'The FN P90 is a compact bullpup PDW firing the high‑velocity 5.7×28mm cartridge from a distinctive 50‑round top‑mounted magazine, designed for armor‑penetrating performance and close‑quarters maneuverability.'],
        ['id' => 'smg-6', 'name' => 'KRISS Vector', 'price' => 135600, 'image' => 'kriss.png', 'description' => 'The KRISS Vector is a modern SMG/carbine (introduced c.2009) using the patented "Super V" system to redirect recoil downward and markedly reduce muzzle climb and felt recoil.']

    ],
    'shotgun' => [
        ['id' => 'shotgun-1', 'name' => 'Remington 870', 'price' => 35000, 'image' => 'remington.png', 'description' => 'The Remington 870 is a rugged, reliable pump-action shotgun commonly chambered in 12 gauge (also available in other gauges), prized for its versatility in hunting, law-enforcement, and home-defense roles.'],
        ['id' => 'shotgun-2', 'name' => 'Browning Auto-5', 'price' => 35850, 'image' => 'browning.png', 'description' => 'The Browning Auto-5 is a classic long-recoil semi-automatic shotgun, commonly in 12 gauge, famous for its distinctive humpback receiver and reliable performance in hunting and sport shooting.'],
        ['id' => 'shotgun-3', 'name' => 'Benelli M4', 'price' => 35600, 'image' => 'benelli.png', 'description' => 'Benelli is an Italian shotgun maker best known for reliable 12-gauge semi-automatic designs—using inertia-driven and ARGO gas systems—highlighted by the M4; tube capacities commonly range from 3–8 rounds and models are popular for tactical, hunting, and competition use.'],
        ['id' => 'shotgun-4', 'name' => 'Winchester 1300', 'price' => 36200, 'image' => 'winchester.png', 'description' => 'The Winchester 1300 is a fast, reliable pump-action shotgun, commonly chambered in 12 gauge, favored for hunting, sport shooting, and law-enforcement duty for its simple, durable design.'],
        ['id' => 'shotgun-5', 'name' => 'Mossberg 500', 'price' => 36150, 'image' => 'mossberg.png', 'description' => 'The Mossberg 500/590 series are rugged pump-action 12-gauge shotguns with tubular magazines (typically 4–8 rounds), valued for reliability, affordability, and widespread use in home defense, law enforcement, and hunting.'],
        ['id' => 'shotgun-6', 'name' => 'Franchi SPAS-12', 'price' => 35650, 'image' => 'franchi.png', 'description' => 'The Franchi SPAS-12 is a 12-gauge shotgun with both pump and semi-automatic modes, known for its unique design and versatility in tactical, sporting, and hunting roles.'],
        ['id' => 'shotgun-7', 'name' => 'Stoeger M3000', 'price' => 37800, 'image' => 'stoeger.png', 'description' => 'Stoeger is a value-oriented shotgun brand producing pump-action and semi-automatic 12-gauge models for hunting and sport, offering decent reliability at an affordable price.']

    ],
    'rifle' => [
        ['id' => 'rifle-1', 'name' => 'AK-47', 'price' => 45200, 'image' => 'ak47.png', 'description' => 'The AK-47 is a Kalashnikov-family 7.62×39mm gas-operated rifle with a long-stroke piston and detachable ~30-round magazine, famed for its extreme reliability, simple design, and widespread global use.'],
        ['id' => 'rifle-2', 'name' => 'FN SCAR', 'price' => 43500, 'image' => 'fnscar.png', 'description' => 'The FN SCAR is a modular combat-rifle family from FN Herstal, available in 5.56×45mm (SCAR-L) and 7.62×51mm (SCAR-H), featuring a gas-piston system, folding stock, quick-change barrels, and ambidextrous controls for special-forces use.'],
        ['id' => 'rifle-3', 'name' => 'M16', 'price' => 44950, 'image' => 'm16.png', 'description' => 'The M16 is a U.S. military 5.56×45mm selective-fire rifle family using a direct-impingement gas system with 20–30-round magazines, widely fielded in service variants such as the M16A1, A2, and A4.'],
        ['id' => 'rifle-4', 'name' => 'AR-15', 'price' => 44700, 'image' => 'ar15.png', 'description' => 'The AR-15 is a semi-automatic civilian rifle platform commonly chambered in .223/5.56 NATO, featuring direct-impingement or piston operation and detachable magazines, prized for its modularity and widespread use in sport, hunting, and personal defense.'],
        ['id' => 'rifle-5', 'name' => 'Steyr AUG', 'price' => 43200, 'image' => 'steyr.png', 'description' => 'The Steyr AUG is a bullpup-configured 5.56×45mm NATO select-fire rifle featuring an integrated optical sight and detachable 30‑round magazines, prized for its compact overall length and widespread service use by several countries.'],
        ['id' => 'rifle-6', 'name' => 'Ruger 10/22', 'price' => 43300, 'image' => 'ruger.png', 'description' => 'The Ruger 10/22 is a semi-automatic .22 LR rimfire carbine featuring a 10‑round rotary magazine, a cold hammer-forged barrel, and extensive modularity and aftermarket support, making it popular for plinking, small-game hunting, and training.'],
        ['id' => 'rifle-7', 'name' => 'Remington 700', 'price' => 43450, 'image' => 'remington700.png', 'description' => 'The Remington 700 is a bolt-action centerfire rifle offered in many calibers, renowned for its accuracy and reliability and widely used for hunting, precision/competition shooting, and as the basis for military and law‑enforcement sniper variants.']

    ],
    'sniper' => [
        ['id' => 'sniper-1', 'name' => 'Barrett M82', 'price' => 76200, 'image' => 'barrett.png', 'description' => 'The Barrett M82 ("Light Fifty") is a U.S.-developed semi-automatic .50 BMG anti-materiel rifle—recoil-operated with a rotating bolt, a large multi-chamber muzzle brake, and a two-piece stamped-steel receiver joined by cross-pins—fed from a 10-round detachable box magazine and fitted with scope mounts and backup iron sights, used to engage materiel and personnel at long ranges.'],
        ['id' => 'sniper-2', 'name' => 'Accuracy International AXMC', 'price' => 78000, 'image' => 'axmc.png', 'description' => 'The Accuracy International AXMC is a British bolt‑action, multi‑caliber sniper system with quick‑change barrel, bolt and magazine for rapid conversion (.338 Lapua, .300 Win Mag, .308), featuring a flat‑bottom steel action, folding stock with adjustable cheekpiece, Picatinny forend, and a two‑stage trigger, prized for accuracy and ruggedness.'],  
        ['id' => 'sniper-3', 'name' => 'CheyTac M200 Intervention', 'price' => 75500, 'image' => 'cheytac.png', 'description' => 'The CheyTac M200 Intervention is an American bolt‑action extreme long‑range rifle chambered for proprietary .408 or .375 CheyTac cartridges, fed from a 7‑round detachable box magazine, featuring a fully adjustable stock with built‑in monopod and typically paired with ballistic‑computing fire‑control systems for precision engagements beyond 2,000 m.'],
        ['id' => 'sniper-4', 'name' => 'Sako TRG 42', 'price' => 77900, 'image' => 'sako.png', 'description' => 'The Sako TRG-42 is a Finnish bolt‑action long‑range rifle chambered in .300 Winchester Magnum and .338 Lapua Magnum, featuring a cold hammer‑forged barrel and receiver, a smooth three‑lug 60° bolt, and a fully adjustable aluminum‑reinforced synthetic stock with an improved recoil pad for precision tactical and competition use.'], 
        ['id' => 'sniper-5', 'name' => 'Daniel Defense Delta 5 Pro', 'price' => 77200, 'image' => 'daniel.png', 'description' => 'The Daniel Defense Delta 5 Pro is an American bolt‑action long‑range rifle promising sub‑0.5 MOA with match ammunition, featuring a lightweight skeletonized chassis, cold‑hammer‑forged interchangeable barrel, three‑lug 60° bolt, Timney Elite trigger, integrated Arca rail and highly adjustable stock, and using AICS‑style detachable magazines.'],
        ['id' => 'sniper-6', 'name' => 'Desert Tech SRS-A2', 'price' => 78800, 'image' => 'desert.png', 'description' => 'The Desert Tech SRS‑A2 is a compact American bullpup bolt‑action multi‑caliber precision rifle with a full‑length barrel, quick‑conversion barrel/bolt/magazine system, a lighter M‑LOK chassis, field‑match flat trigger, and an integral tripod mount.']

    ],
    'LMG' => [
        ['id' => 'lmg-1', 'name' => 'M250', 'price' => 199200, 'image' => 'm250.png', 'description' => 'The M250 is a U.S. Army Next‑Generation Squad Weapon-era lightweight, gas‑operated, belt‑fed machine gun chambered in 6.8×51mm SIG Fury, adopted to replace the M249 SAW for improved range and lethality.'],
        ['id' => 'lmg-2', 'name' => 'FN MINIMI Mk3', 'price' => 198500, 'image' => 'mk3.png', 'description' => 'The FN MINIMI Mk3 is a modern light machine gun in 5.56×45mm and 7.62×51mm with ergonomic and mobility upgrades over earlier MINIMI variants, widely used worldwide.'],
        ['id' => 'lmg-3', 'name' => 'Heckler & Koch MG5', 'price' => 199900, 'image' => 'mg5.png', 'description' => 'The Heckler & Koch MG5 is a 7.62×51mm NATO general‑purpose machine gun adopted by Germany in 2015 to replace the MG3, designed for modularity, improved ergonomics, and enhanced accuracy.'],
        ['id' => 'lmg-4', 'name' => 'PKP Pecheneg', 'price' => 200100, 'image' => 'pkp.png', 'description' => 'The PKP Pecheneg is a Russian 7.62×54mmR general‑purpose machine gun derived from the PKM, featuring a heavy non‑removable forced‑air‑cooled barrel for sustained infantry‑support fire and entered service in 2001.'],
        ['id' => 'lmg-5', 'name' => 'Knights Armament Company (KAC)', 'price' => 198500, 'image' => 'kac.png', 'description' => 'The Knights Armament Company LMG family (LAMG/AMG) are lightweight 5.56×45mm and 7.62×51mm machine guns featuring a constant‑recoil system for reduced recoil and superior controllability, prized for advanced design despite limited widespread adoption.'],
        ['id' => 'lmg-6', 'name' => 'IWI Negev NG7', 'price' => 200900, 'image' => 'iwi.png', 'description' => 'The IWI Negev NG7 is an Israeli 7.62×51mm light machine gun—an upscaled Negev designed for versatile use on bipod (LMG role) or tripod (sustained‑fire), prized for its compactness and adaptability.']

    ],
    'melee' => [
        ['id' => 'melee-1', 'name' => 'KA-BAR Fighting Utility Knife', 'price' => 6000, 'image' => 'kabar.png', 'description' => 'The KA-BAR Fighting Utility Knife is a classic USMC combat and utility knife from WWII featuring a tough clip‑point steel blade and stacked leather handle, prized for fighting and field tasks.'],
        ['id' => 'melee-2', 'name' => 'Fairbairn–Sykes Fighting Knife', 'price' => 5500, 'image' => 'fairbairn.png', 'description' => 'The Fairbairn–Sykes fighting knife is a slim, double‑edged dagger developed for British commandos in WWII and optimized for quick thrusting in close‑quarters combat.'],
        ['id' => 'melee-3', 'name' => 'Bowie Knife', 'price' => 5900, 'image' => 'bowie.png', 'description' => 'The Bowie knife is a large fixed‑blade, clip‑point knife popularized in the 19th century by James Bowie and James Black and commonly used for hunting and general utility.'],  
        ['id' => 'melee-4', 'name' => 'Swiss Army Knife', 'price' => 4700, 'image' => 'swiss.png', 'description' => 'The Swiss Army Knife is a compact multi-tool by Victorinox featuring blades, screwdrivers, bottle openers, and other tools for versatile everyday use.'],
        ['id' => 'melee-5', 'name' => 'Kukri', 'price' => 5400, 'image' => 'kukri.png', 'description' => 'The Kukri is a traditional Nepalese curved blade knife used by Gurkhas for combat and utility purposes.'],
        ['id' => 'melee-6', 'name' => 'Eickhorn KM4000', 'price' => 5100, 'image' => 'eickhorn.png', 'description' => 'The Eickhorn KM4000 is a German combat/utility knife featuring a corrosion‑resistant tanto‑style blade with a sawback spine, integrated wire‑cutting/sheath functions, a rugged synthetic handle with glass‑breaker, and a MOLLE‑compatible sheath.']

    ],
    'loadout' => [
        ['id' => 'lo-1', 'name' => 'Tear Gas', 'price' => 4850, 'image' => 'teargas.png', 'description' => 'Tear gas is an aerosol or pyrotechnic chemical irritant that causes intense eye and respiratory irritation to disperse crowds, is used by police and military for riot control, and can be dangerous with prolonged or concentrated exposure and is legally restricted in many jurisdictions.'],
        ['id' => 'lo-2', 'name' => 'M18 (Smoke grenade)', 'price' => 7500, 'image' => 'smoke.png', 'description' => 'A smoke grenade produces dense obscuring smoke for screening, signaling, or marking, is used by military and emergency services, and can be hazardous if inhaled or misused and is subject to regulation and restricted use by trained personnel.'],
        ['id' => 'lo-3', 'name' => 'M84 (Flashbang)', 'price' => 9790, 'image' => 'flashbang.png', 'description' => 'A flashbang (stun grenade) is a non‑lethal disorientation device that produces an intense flash and loud blast to temporarily incapacitate and disorient occupants during entry or breaching, is used by military and police for close‑quarters clearing, and can cause serious injury if used improperly and is restricted to trained personnel.'],
        ['id' => 'lo-4', 'name' => 'First Aid Kit', 'price' => 10900, 'image' => 'fak.png', 'description' => 'The First Aid Kit is a personal soldier’s pouch containing tourniquets, bandages, and other medical supplies for rapid, one‑handed treatment of life-threatening injuries in the field.'],
        ['id' => 'lo-5', 'name' => 'Night Vision Goggles', 'price' => 9990, 'image' => 'goggles.png', 'description' => 'Night Vision Goggles (NVG) are helmet-mounted devices that allow soldiers to see in low-light or darkness, providing a tactical advantage during nighttime operations.'],
        ['id' => 'lo-6', 'name' => 'Tactical Pouch', 'price' => 5590, 'image' => 'pouch.png', 'description' => 'A Tactical Pouch is a modular, removable bag attached to a vest, pack, or belt for carrying magazines, grenades, tools, or other small gear for quick access.'],
        ['id' => 'lo-7', 'name' => 'Gun Sling', 'price' => 7700, 'image' => 'sling.png', 'description' => 'A Gun Sling is a strap worn around the body or neck to carry and stabilize a rifle, allowing comfortable transport and quick readiness for use.'],
        ['id' => 'lo-8', 'name' => '40mm under-barrel grenade launcher', 'price' => 10200, 'image' => 'underbarrel.png', 'description' => 'Underbarrel attachments—such as 40mm grenade launchers (e.g., M203), shotgun modules, and weapon-mounted lights—mount beneath a rifle barrel to add capability without replacing the primary weapon, enhancing versatility while requiring proper training and integration.'],
        ['id' => 'lo-9', 'name' => 'Standalone 40 mm launcher', 'price' => 10350, 'image' => 'standalone.png', 'description' => 'A standalone grenade launcher (e.g., Milkor MGL) is a shoulder‑fired multi‑shot (commonly 6×40mm) or single‑shot weapon that provides area or indirect fire where an underbarrel option isn’t fitted, requiring trained operators and appropriate doctrine.'],
        ['id' => 'lo-10', 'name' => 'Multi-launcher', 'price' => 11000, 'image' => 'mlauncher.png', 'description' => 'A grenade launcher (e.g., M203, M79, M32) is a device that fires 40mm grenades—available in single‑shot or multi‑shot, underbarrel or standalone configurations—to deliver explosive, smoke, or less‑lethal munitions at extended ranges and is employed by trained military or law‑enforcement units.'],
        ['id' => 'lo-11', 'name' => 'TASER X26P', 'price' => 12800, 'image' => 'taser.png', 'description' => 'A Taser is a conducted electrical weapon (CEW) that delivers short, high‑voltage/low‑current pulses to induce temporary neuromuscular incapacitation, is available in contact and probe‑firing models with varying ranges, and is used by law enforcement for less‑lethal compliance subject to legal and policy restrictions.'],
        ['id' => 'lo-12', 'name' => 'FN 303', 'price' => 14700, 'image' => 'fn303.png', 'description' => 'The FN 303 is a semi‑automatic, compressed‑air less‑lethal launcher that fires fin‑stabilized .68‑caliber projectiles from a 15‑round detachable drum to deliver impact, paint, or irritant effects for crowd control and marking at ranges up to ~50 m and is intended for trained law‑enforcement and military use.']

    ]
];

// section descriptions 
$section_descriptions = [
    'pistol' => 'A handheld firearm designed for self defense or target shooting, typically with a short barrel and magazine holding multiple rounds',
    'revolver' => 'A handheld firearm with a rotating cylinder holding multiple cartridges, known for its reliability and simplicity',
    'SMG' => 'A compact automatic firearm firing pistol‑caliber cartridges, optimized for close‑quarters maneuverability and a high rate of fire',
    'shotgun' => 'A long-barreled firearm designed to shoot a spread of pellets or a single slug, commonly used for hunting and sport shooting',
    'rifle' => 'A long-barreled firearm designed for precision shooting, often used for hunting, sport shooting, and military applications',
    'sniper' => 'A precision long‑range rifle (bolt or semi‑automatic) built for extreme accuracy and single‑shot engagement at extended distances',
    'LMG' => 'A squad‑support automatic weapon (belt‑ or magazine‑fed) providing sustained suppressive fire for area denial and unit support',
    'melee' => 'A hand‑held close‑combat weapon used for silent or immediate short‑range engagement',
    'loadout' => 'A tailored set of weapons, gear, non-lethal ordnance, and equipment prepared for a specific combat role or mission'
];
?>